apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mern-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mosrichard1234/cicd-tf-vpc-actions-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: mongodb://admin:admin123@mongodb-service:27017/appdb?authSource=admin
---

apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: mern-app
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
